### ISSUE TITLE
502 error in response - submitted order

### ISSUE THREAD

**Issue by aghamir** [veox/python3-krakenex#98] opened 2018-08-28 08:16 UTC
### Versions

```
OS:   Ubuntu
Python:   3
krakenex: 2.1.0
```

### What are you trying to achieve?
I want to addOrder via krakenex. It returns 502 error in response. So I re-send request later.

### What do you expect to happen?
I expect that when krakenex return the 502 error, order won't be added in kraken. 

### What happens instead?
I saw duplicated order in my kraken.

I saw #66, however, I don't understand how can I avoid this.

**Comment by veox** [comment] 2018-08-28 08:53
Darn. This means the remote end is experiencing overloads again.

See [this old(ish) PSA](https://www.reddit.com/r/krakenex/comments/778uvh/psa_http_error_502_does_not_mean_the_query_wont/) with an explanation.

On the upside, this may present an opportunity to finally implement retrying failed requests, without looking for a "flaky HTTP server" mock for tests first.

-----

There are currently two implementations [in the PR section](https://github.com/veox/python3-krakenex/pulls) that have been hanging there since the last time it was commonplace. (Note they're both against an earlier version of `krakenex` (`v2.0.0`, I believe), so both have merge conflicts.)

However, for `502`, though, they would (should!..) return the same error as you're getting now - precisely for the reason that the behaviour can't be said to be deterministic, at least not without an arbitrarily long wait period (as described in the PSA).

**Comment by veox** [comment] 2021-02-28 14:44
Closing as duplicate of issue #66.

**Closed by veox** 2021-02-28 14:44 UTC
Labels: duplicate, question
